# this is only for search engines, it does not appear in the home
# as long as the json variables name and description are provided
title: HHS CS Club
description: HHS Computer Science Club Website.
baseurl: "https://docs.google.com/forms/d/1JBcERG3sohKR7o9awkdlu70iLK5bV5LVteRpVtEzmKA/edit"
url: https://hhscs.club

# this information is shown on the homepage, all fields are optional and
# can be declared either as a single string or as a string array/hash
json:
  name: HHS Computer Science
  description:
    - Howdy
    - pls join cs club
    - kinda 🔥 fr
    - (links below)
  cv: homesteadprogramming@gmail.com
  address:
    - Tuesday Lunch
    - Room i5 (Mr. Shelby's room)
  contact:
    president: Armaan Gomes
    secretary/treasurer: Aayush Gaywala
    workshop/community_director: Kevin Chang
    competitions/website_director: Akshay Giri
    hackathons/events_director: Alicia Chu
  demo: cool stuff, and more stuff, and some other programming stuff
  source: Send them to our discord
  profiles:
    email_list: https://docs.google.com/forms/d/1JBcERG3sohKR7o9awkdlu70iLK5bV5LVteRpVtEzmKA/edit
    discord: https://discord.gg/MMPh8zwDqN
    instagram: https://www.instagram.com/hhscomputerscience/

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
